from openai import OpenAI
import json
from pathlib import Path

# Configuration - set NVIDIA_API_KEY env var, or use either API key
import os
API_KEY = os.environ.get("NVIDIA_API_KEY", "")  # inkling - good for structured JSON
BASE_URL = "https://integrate.api.nvidia.com/v1"
MODEL = "thinkingmachines/inkling"

palettes_dir = Path(r"G:\Mandala Rendering Software\daniel_blueprint\styles\anime\v1\palettes")

def generate_palettes(num_palettes=5, styles=None):
    """Generate anime color palettes using NVIDIA API."""
    
    if styles is None:
        styles = ["mecha", "magical_girl", "horror", "slice_of_life", "cyberpunk"]
    
    client = OpenAI(
        base_url=BASE_URL,
        api_key=API_KEY
    )
    
    generated = []
    
    for i in range(num_palettes):
        style = styles[i % len(styles)]
        
        prompt = f"""Generate 1 anime color palette for {style} sub-genre.
        Provide JSON with this exact format:
        {{
          "palette_name": "string",
          "skin": "#RRGGBB",
          "hair": "#RRGGBB", 
          "eyes": "#RRGGBB",
          "accent": "#RRGGBB",
          "notes": "brief description"
        }}
        Colors should be valid hex codes suitable for anime character design.
        Make each palette distinct and appropriate for the {style} genre.
        """
        
        try:
            completion = client.chat.completions.create(
                model=MODEL,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.7,
                max_tokens=1024,
                stream=False
            )
            
            response = completion.choices[0].message.content
            # Try to parse JSON from response
            try:
                palette_data = json.loads(response)
                generated.append(palette_data)
                print(f"[{i+1}/{num_palettes}] {style}: {palette_data.get('palette_name', 'Unnamed')}")
            except json.JSONDecodeError:
                print(f"[{i+1}/{num_palettes}] {style}: JSON parse failed, raw output: {response[:100]}")
                
        except Exception as e:
            print(f"[{i+1}/{num_palettes}] {style}: Error - {str(e)[:80]}")
    
    return generated

# Generate palettes for all requested sub-genres
print(f"Generating {5} anime sub-genre palettes using {MODEL}...")
palettes = generate_palettes(num_palettes=5, styles=["mecha", "magical_girl", "horror", "slice_of_life", "cyberpunk"])

# Save to directory
print(f"\nSaving {len(palettes)} palettes to {palettes_dir}...")
for p in palettes:
    palette_name = p.get("palette_name", "unnamed").replace(" ", "_").replace("/", "_")
    palette_id = f"anime.nvidia.{palette_name.lower()}.v1"
    
    # Convert hex colors to RGB tuples
    colors = []
    for hex_color in [p.get("skin"), p.get("hair"), p.get("eyes"), p.get("accent")]:
        if hex_color and hex_color.startswith("#"):
            hex_stripped = hex_color.lstrip("#")
            r = int(hex_stripped[0:2], 16) / 255.0
            g = int(hex_stripped[2:4], 16) / 255.0
            b = int(hex_stripped[4:6], 16) / 255.0
            colors.append([r, g, b, 1.0])
        else:
            colors.append([0.5, 0.5, 0.5, 1.0])  # fallback gray
    
    write_data = {
        "name": p.get("palette_name", palette_name),
        "palette_id": palette_id,
        "colors": colors,
        "shadow_multiplier": 0.45,
        "highlight_boost": 1.1,
        "rim_color": [1.0, 1.0, 1.0, 1.0],
        "line_color": [0.0, 0.0, 0.0, 1.0],
        "quantization_levels": 5,
        "notes": p.get("notes", f"{palette_name} anime palette generated by NVIDIA API")
    }
    
    filepath = palettes_dir / f"{palette_id}.json"
    with open(filepath, 'w') as f:
        json.dump(write_data, f, indent=2)
    print(f"  Saved: {filepath.name}")

print(f"\nComplete! {len(palettes)} palettes generated and saved.")