[pytest]
asyncio_mode = auto
markers =
    asyncio: mark test as async
pythonpath =
    sme-txt
    sme-aud
    sme-vis
    sme-gen
    sme-vid
    sme-log
    sme-core/src
testpaths =
    sme-core/tests
    sme-txt/tests
    sme-aud/tests
    sme-vis/tests
    sme-gen/tests
    sme-vid/tests
    sme-log/tests
